apiVersion: v1
kind: ReplicationController
metadata:
  name: clamav
  namespace: clamav
  labels:
    name: clamav
spec:
  replicas: 2
  selector:
    name: clamav
  template:
    metadata:
      labels:
        name: clamav
    spec:
      containers:
        - name: clamd
          image: harbor.pytheascapital.net/pytheas/clamav:latest
          env:
            - name: FRESHCLAM_CHECKS
              value: "6"
          ports:
            - containerPort: 3310
              name: api
              protocol: TCP
          resources:
            requests:
              cpu: 1000m
              memory: 2000M
            limits:
              cpu: 1000m
              memory: 3000M
          livenessProbe:
            exec:
              command:
                - /readyness.sh
            initialDelaySeconds: 20
            timeoutSeconds: 2
          readinessProbe:
            exec:
              command:
                - /readyness.sh
            initialDelaySeconds: 90
            timeoutSeconds: 10
            periodSeconds: 30
            failureThreshold: 10
